### ISSUE TITLE
Log?

### ISSUE THREAD

**Issue by ddugovic** [dolegi/lichess-bot#1]
I attempted to play a chess960 game against my bot (Stockfish supports every Lichess variant), and I don't know what went wrong:
https://lichess.org/Bg5bUFlW

**Comment by dolegi** [comment]
The bot logs to `stdout`. How where you running it?

**Comment by dolegi** [comment]
I have a bot using it with standard variant here https://lichess.org/@/dolegibot
I'll try out with chess960 later

**Comment by dolegi** [comment]
Thanks for trying the bot and raising this issue 😄 . This is now fixed in with the latest code changes. I've deployed the changes to https://lichess.org/@/dolegibot and you can challenge it to `chess960` to test
